-- MySQL Script generated by MySQL Workbench
-- Tue Jun  7 17:53:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema impuestos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema impuestos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `impuestos` DEFAULT CHARACTER SET utf8 ;
USE `impuestos` ;

-- -----------------------------------------------------
-- Table `impuestos`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `impuestos`.`rol` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `impuestos`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `impuestos`.`usuario` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Cedula` INT(25) NOT NULL,
  `Nombres` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Usuario` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(60) NOT NULL,
  `Estado` VARCHAR(45) NOT NULL DEFAULT 'Activo',
  `Rol_id` INT(11) NOT NULL,
  `Telefono` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Id`, `Rol_id`),
  UNIQUE INDEX `cedula_UNIQUE` (`Cedula` ASC) ,
  UNIQUE INDEX `Correo_UNIQUE` (`Email` ASC) ,
  INDEX `fk_Administradores_Rol_idx` (`Rol_id` ASC) ,
  CONSTRAINT `fk_Administradores_Rol`
    FOREIGN KEY (`Rol_id`)
    REFERENCES `impuestos`.`rol` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `impuestos`.`industria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `impuestos`.`industria` (
  `Id` INT(11) NOT NULL,
  `NIT` INT(11) NOT NULL,
  `NumeroPlaca` INT(11) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `EsTienda` TINYINT(4) NOT NULL,
  `InicioActividad` DATETIME NOT NULL,
  `TipoRegimen` VARCHAR(45) NOT NULL,
  `TipoPersona` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Avaluo` VARCHAR(45) NOT NULL,
  `Propietario` INT(11) NOT NULL,
  PRIMARY KEY (`Id`, `Propietario`),
  INDEX `fk_industria_usuario1_idx` (`Propietario` ASC) ,
  CONSTRAINT `fk_industria_usuario1`
    FOREIGN KEY (`Propietario`)
    REFERENCES `impuestos`.`usuario` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `impuestos`.`predial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `impuestos`.`predial` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `NumeroCuenta` VARCHAR(45) NOT NULL,
  `Avaluo` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(60) NOT NULL,
  `Destino` VARCHAR(45) NOT NULL,
  `AreaTerritorio` VARCHAR(45) NOT NULL,
  `Estrato` VARCHAR(45) NULL DEFAULT NULL,
  `AreaConstruida` VARCHAR(45) NOT NULL,
  `Propietario` INT(11) NOT NULL,
  PRIMARY KEY (`Id`, `Propietario`),
  UNIQUE INDEX `numeroCuenta_UNIQUE` (`NumeroCuenta` ASC) ,
  INDEX `fk_Predial_Administrador1_idx` (`Propietario` ASC) ,
  CONSTRAINT `Propietario`
    FOREIGN KEY (`Propietario`)
    REFERENCES `impuestos`.`usuario` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


INSERT INTO `impuestos`.`rol` (`Id`, `Rol`) VALUES (1, 'Superadministrador'), 
                                                   (2, 'Administrador'), 
                                                   (3, 'Usuario');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
