-- MySQL Script generated by MySQL Workbench
-- Tue May 17 08:55:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema impuestos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema impuestos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `impuestos` DEFAULT CHARACTER SET utf8 ;
USE `impuestos` ;

-- -----------------------------------------------------
-- Table `impuestos`.`Administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `impuestos`.`Administradores` (
  `Id` INT NOT NULL,
  `Cedula` INT NOT NULL,
  `Nombres` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Usuario` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(60) NOT NULL,
  `Rol_id` INT NOT NULL,
  PRIMARY KEY (`Id`, `Rol_id`),
  UNIQUE INDEX `cedula_UNIQUE` (`Cedula` ASC) VISIBLE,
  UNIQUE INDEX `Correo_UNIQUE` (`Email` ASC) VISIBLE,
  INDEX `fk_Administradores_Rol_idx` (`Rol_id` ASC) VISIBLE,
  CONSTRAINT `fk_Administradores_Rol`
    FOREIGN KEY (`Rol_id`)
    REFERENCES `mydb`.`Rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `impuestos`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `impuestos`.`Rol` (
  `id` INT NOT NULL,
  `Rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
